name: Update popular subreddits

on:
  schedule:
    - cron: '0 0 * * 0,3'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-popular-subreddits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run gen_popular.py
      run: python scripts/gen_popular.py > popular.txt
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add popular.txt
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Popular subreddits weekly update [$(date +'%Y-%m-%d')]"
          git push
        fi